### ISSUE TITLE
[BUG] wg0.conf is not found

### ISSUE THREAD

**Issue by sakmalh** [linuxserver/docker-wireguard#271] opened 2023-06-15 16:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are some errors in the logs of wiregaurd pod. I am running this in a kubernetes cluster. The reason to have wiregaurd in our cluster is so I can connect to the MongoAtlas which is connected to the cluster using private endpoint. I can whitelist the wiregaurd ip address and the developers can connect to the VPN to use the mongodb

### Steps To Reproduce

1. Applied the secret.yaml
2. Applied the deployment.yaml
3. Applied the service.yaml

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: example
spec:
  selector:
    matchLabels:
      name: wireguard
  template:
    metadata:
      labels:
        name: wireguard
    spec:
      initContainers:
        # The exact name of the network interface needs to be stored in the
        # wg0.conf WireGuard configuration file, so that the routes can be
        # created correctly.
        # The template file only contains the "ENI" placeholder, so when
        # bootstrapping the application we'll need to replace the placeholder
        # and create the actual wg0.conf configuration file.
        - name: "wireguard-template-replacement"
          image: "busybox"
          command: ["sh", "-c", "ENI=$(ip route get 8.8.8.8 | grep 8.8.8.8 | awk '{print $5}'); sed \"s/ENI/$ENI/g\" /etc/wireguard-secret/wg0.conf.template > /etc/wireguard/wg0.conf; chmod 400 /etc/wireguard/wg0.conf"]
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard/
            - name: wireguard-secret
              mountPath: /etc/wireguard-secret/

      containers:
        - name: "wireguard"
          image: "linuxserver/wireguard:latest"
          ports:
            - containerPort: 51820
          env:
            - name: "TZ"
              value: "Europe/Berlin"
            # Keep the PEERS environment variable to force server mode
            - name: "PEERS"
              value: "example"
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard/
              readOnly: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN

      volumes:
        - name: wireguard-config
          emptyDir: {}
        - name: wireguard-secret
          secret:
            secretName: wireguard

      imagePullSecrets:
        - name: docker-registry
        
-----

apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: example
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    Address = 172.16.16.0/20
    ListenPort = 51820
    PrivateKey = OIviMX9BPHk1w/bvsXW0Qc2/mY3+HS3iS31aEtsn+Uc=
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ENI -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ENI -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0

    [Peer]
    # Example Peer 1
    PublicKey = AOIzLd2C71DtY8DWgUfuMllRNa0iR1O3tO2WbFO7ICU=
    AllowedIPs = 172.16.16.10
    
-----------

apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: example
spec:
  type: LoadBalancer
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    name: wireguard
```
Service of wiregaurd 
```
wireguard                                            LoadBalancer   100.69.238.69    <pending>                                                                      51820:32007/UDP   44m
```
```


### Container logs

```bash
Defaulted container "wireguard" out of: wireguard, wireguard-template-replacement (init)
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

Uname info: Linux wireguard-698b74d757-lb22h 5.15.0-1026-aws #30~20.04.2-Ubuntu SMP Fri Nov 25 14:53:22 UTC 2022 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
rm: cannot remove '/etc/wireguard/wg0.conf': Read-only file system
ln: failed to create symbolic link '/etc/wireguard/wg0.conf': File exists
**** Server mode is selected ****
**** SERVERURL var is either not set or is set to "auto", setting external IP to auto detected value of 13.250.43.221 ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** No wg0.conf found (maybe an initial install), generating 1 server and example peer/client confs ****
PEER example QR code (conf file is saved under /config/peer_example):


QR CODE



[custom-init] No custom files found, skipping...
.:53
CoreDNS-1.10.0
linux/amd64, go1.19.9, 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.16.0/20 dev wg0
[#] ip link set mtu 8901 up dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
[#] sysctl -w -q net.ipv4.ip_forward=1
[ls.io-init] done.

```
```

**Comment by aptalca** [comment] 2023-06-15 17:09
`/etc/wireguard/` is not a mount path we use or accept

**Comment by sakmalh** [comment] 2023-06-15 17:12
Can I know how to configure that?

**Comment by aptalca** [comment] 2023-06-15 17:26
It's all in the readme

`/config`

**Comment by sakmalh** [comment] 2023-06-16 12:49
hey @aptalca 
Thanks for that. I made it up and running successfully with peers.
```
Uname info: Linux wireguard-5f96477b9c-8dprj 5.15.0-1026-aws #30~20.04.2-Ubuntu SMP Fri Nov 25 14:53:22 UTC 2022 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** SERVERURL var is either not set or is set to "auto", setting external IP to auto detected value of 18.141.177.255 ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** Server mode is selected ****
**** Server related environment variables changed, regenerating 1 server and akmal peer/client confs ****
PEER akmal QR code (conf file is saved under /config/peer_akmal):
QR CODE HERE
[custom-init] No custom files found, skipping...
.:53
CoreDNS-1.10.0
linux/amd64, go1.19.9, 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 8901 up dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
[ls.io-init] done.

```

But when I apply the service.yaml mentioned above its still on pending. Our cluster is setup in AWS EC2 with Kops. It uses nginx loadbalancer.

**Comment by aptalca** [comment] 2023-06-16 13:18
> its still on pending

I don't know what that means but according to the logs, wireguard is up and running

**Comment by sakmalh** [comment] 2023-06-16 13:30
```
wireguard  LoadBalancer   100.66.172.221   <pending>             51820:32017/UDP   37m
```
Can I know how to expose the wiregaurd in a kubernetes with aws loadbalancer setup with nginx . 

Thank you for your help @aptalca

**Comment by aptalca** [comment] 2023-06-16 13:34
That's beyond the scope of this repo and its related issues.

Feel free to seek help from the community on our discord's `#other-support` channel

Closing as it's not a bug

**Closed by aptalca** 2023-06-16 13:34 UTC

**Comment by sakmalh** [comment] 2023-06-16 13:39
Thanks for your help
