### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by Fossil01** [linuxserver/docker-wireguard#41] opened 2020-06-22 08:54 UTC
It would be nice to have native IPv6 support with config generation etc.

I have added PostUp and Down rules to my template but it does not listen on IPv6 by default. Not sure how I should add that to server.conf template too.

`Address = ${INTERFACE}.1`

`ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`

**Comment by aptalca** [comment] 2020-06-22 12:59
Stop the container, edit wg0.conf and restart. The change will be persistent as long as you don't change one of the server variables like peers, ip, port, etc. which would result in regeneration of wg0.conf

**Comment by Fossil01** [comment] 2020-06-22 12:59
So you'd just add an IPv6 listening addr to it?

**Comment by aptalca** [comment] 2020-06-22 21:42
No idea. I don't use or have access to ipv6. You sounded like you knew what you were doing.

**Comment by drizuid** [comment] 2020-06-25 15:08
duplicate of https://github.com/linuxserver/docker-wireguard/issues/33

**Closed by drizuid** 2020-06-25 15:08 UTC
