### ISSUE TITLE
net.ipv4.conf.all.src_valid_mark invalid

### ISSUE THREAD

**Issue by jellyfinuser** [linuxserver/docker-wireguard#102] opened 2021-03-09 10:53 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When I execute docker-compose wireguard with config , running until a month ago without problems
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

## Current Behavior
It not work now, this docker-compose was running until a month ago, after last update it show error and no start

## Steps to Reproduce

1. Execute docker-compose -f wireguard.yml up -d
2.
3.
4.

## Environment
**OS:** Linux raspberrypi 5.10.17-v7l+
**CPU architecture:** armv7l
**How docker service was installed:**

Installed from official docker repo, executed like readme file 

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=xxxx.xxxx.xxx #optional
      - SERVERPORT=xxxxxx#optional
      - PEERS=3 #optional
      - PEERDNS=xxxxxxxxx
      - INTERNAL_SUBNET=xxxxxxxxxx/Xx #optional
      - ALLOWEDIPS=xxxxxxxxxx/xx #optional
    volumes:
      - /config:/config
      - /lib/modules:/lib/modules
    ports:
      - xxxxxx:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    network_mode: host
networks:
  wireguard:

## Docker logs
Starting wireguard ... error

ERROR: for wireguard  Cannot start service wireguard: OCI runtime create failed: sysctl "net.ipv4.conf.all.src_valid_mark" not allowed in host network namespace: unknown

ERROR: for wireguard  Cannot start service wireguard: OCI runtime create failed: sysctl "net.ipv4.conf.all.src_valid_mark" not allowed in host network namespace: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by j0nnymoe** [comment] 2021-03-09 11:38
Please provide the information requested in the issue template so that we can help accordingly.

**Comment by jellyfinuser** [comment] 2021-03-09 11:59
Sorry, updated!

**Comment by Mickain26** [comment] 2021-03-10 05:56
Hello,

I have exactly the same problem.
I tried to add --privileged but it doesn't change anything.

I'm running under debina 10.

I have the impression that the problem appeared after an update of Debian.

I tried to uninstall wireguard and its image and reinstall it with this command with -privileged.

`docker run -d \
--net host \
--name=wireguard \
--cap-add=NET_ADMIN \
--cap-add=SYS_MODULE \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Europe/France \
-e SERVERURL=xxxxxxxxxx `#optional` \
-e SERVERPORT=51820 `#optional` \
-e PEERS=5 `#optional` \
-e PEERDNS=auto `#optional` \
-e INTERNAL_SUBNET=10.13.13.0 `#optional` \
-e ALLOWEDIPS=0.0.0.0/0 `#optional` \
-p 51821:51820/udp \
-v /doker/wireguard/config:/config \
-v /lib/modules:/lib/modules \
--sysctl="net.ipv4.conf.all.src_valid_mark=1" \
--restart unless-stopped \
--privileged \
ghcr.io/linuxserver/wireguard`

I get this error message :
`docker: Error response from daemon: OCI runtime create failed: sysctl "net.ipv4.conf.all.src_valid_mark" not allowed in host network namespace: unknown.`

Thanks for your help.

**Comment by aptalca** [comment] 2021-03-10 11:50
It says right there in the log. You can't set that sysctl with host networking

**Comment by blasphemite** [comment] 2021-03-17 21:01
I was having the same problem and seem to have found a working solution. I have two Ubuntu clients with the same config, one was working and the other was experiencing this issue. The nonworking client used `containerd.io-1.4.4-1` and the working client `containerd.io-1.4.3-1`. I downgraded the nonworking client to the lower version and it works again.

Try checking your containerd.io version `apt list containerd.io` and possibly rolling back `apt install containerd.io=1.4.3-1`

Not sure if this identifies a root cause, but this change seems to be working for me.

**Comment by endrift** [comment] 2021-08-28 22:50
I'm also having this issue. Downgrading containerd is not an option for me.

**Comment by aptalca** [comment] 2021-08-28 23:07
Like I said before, that option does not work with host networking as it says in the log. Use bridge networking as instructed in the samples

**Comment by endrift** [comment] 2021-08-28 23:18
Your explanation was lacking at best and condescending at worst. The readme gives a fine explanation for how to set it up if you don't care about, say, the host being able to connect over that interface, but it doesn't explain how to do that if you do care. It also doesn't draw attention to any other examples. It wouldn't kill you to give a better explanation beyond just "you can't do that".

**Comment by aptalca** [comment] 2021-08-29 00:31
If you want the right answers, ask the right questions. The question in this issue is all about the error the user received. The answer I provided is about avoiding that error.

No one asked anything about how to get host services accessing the tunnel. You also added a "me too" on an old question that was already answered.

If you need help with setting routes for host services accessing the tunnel, then please seek help in the correct channels (not github issues) and ask specific questions while detailing your goals and the issues you're having.

I am simply answering questions here. I don't have time to worry about people's feelings.

**Comment by endrift** [comment] 2021-08-29 00:47
Gotten to "condescending at best" territory now I see. Don't have time for feeling but have time for a screed. The issue was not closed, and was marked as invalid for lack of info, which had since been provided. Your answer was not, well, an answer, and provided no information that hadn't already been easily gleaned from reading the logs you so glibly pointed to. I guess I'll be recommending people stay away from this project now, much like I do for other projects where the maintainers are patronizing on the best of days.

**Closed** 2021-08-29 03:02 UTC
Labels: invalid

**Comment by g0d-m0nky** [comment] 2021-08-30 12:20
> If you want the right answers, ask the right questions. The question in this issue is all about the error the user received. The answer I provided is about avoiding that error.
> 
> No one asked anything about how to get host services accessing the tunnel. You also added a "me too" on an old question that was already answered.
> 
> If you need help with setting routes for host services accessing the tunnel, then please seek help in the correct channels (not github issues) and ask specific questions while detailing your goals and the issues you're having.
> 
> I am simply answering questions here. I don't have time to worry about people's feelings.

I have no idea why someone would maintain a public project like this and then be so immature and condescending in the help comments. You could have answered the question first time round. Will also be recommending people to stay away from this project. It is this type of attitude that keeps a lot of people away from self hosting and damages FOS in general.

**Comment by aptalca** [comment] 2021-08-30 12:43
> You could have answered the question first time round.

OP asked about the error they were getting and how to prevent it. The answer simply was "not using host networking", which still remains the correct and accurate answer. There is nothing condescending about it. You cannot use host networking with that specific sysctl set.

I'm being direct, which is quite different than condescending. The reason for that directness is because we are volunteers who do this in our free time.

If you ask "what is 5 divided by zero?" don't expect a math lesson. The answer you'll get is "you cannot divide by zero" and that would not be condescending. It just is the answer.

**Comment by anastazya** [comment] 2022-08-28 21:19
> In my case, I'm using a Class C IP, so I had to change the following for it to work:
> 
> ```diff
> diff --git a/docker-compose.yaml b/docker-compose.yaml
> index 0261a33..350055a 100644
> --- a/docker-compose.yaml
> +++ b/docker-compose.yaml
> @@ -1,24 +1,24 @@
>  ---
>  version: "2.1"
>  services:
>    wireguard:
>      image: lscr.io/linuxserver/wireguard
>      container_name: wireguard
>      cap_add:
>        - NET_ADMIN
>        - SYS_MODULE
>      environment:
>        - PUID=1000
>        - PGID=1000
>        - TZ=Europe/Vienna
>        - SERVERURL=mihai.duckdns.org #optional
>        - SERVERPORT=51820 #optional
>        - PEERS=1 #optional
>        - PEERDNS=auto #optional
> -      - INTERNAL_SUBNET=10.13.13.0 #optional
> +      - INTERNAL_SUBNET=192.168.0.0
>        - ALLOWEDIPS=0.0.0.0/0 #optional
>      ports:
>        - 51820:51820/udp
>      sysctls:
>        - net.ipv4.conf.all.src_valid_mark=1
>      restart: unless-stopped
> ```

And now your VPN clients can connect to the host network bidirectionally ?

**Comment by mihaigalos** [comment] 2022-09-05 18:22
> And now your VPN clients can connect to the host network bidirectionally ?

I only tried from the client->network, which works.

**Comment by guyein** [comment] 2022-11-30 23:25
> > You could have answered the question first time round.
> 
> OP asked about the error they were getting and how to prevent it. The answer simply was "not using host networking", which still remains the correct and accurate answer. There is nothing condescending about it. You cannot use host networking with that specific sysctl set.
> 
> I'm being direct, which is quite different than condescending. The reason for that directness is because we are volunteers who do this in our free time.
> 
> If you ask "what is 5 divided by zero?" don't expect a math lesson. The answer you'll get is "you cannot divide by zero" and that would not be condescending. It just is the answer.

Well I guess the goal of this project for some people here is to install wireguard on the host which is recommended(at least of what I am seeing online).

so my question is what is the sysctl set I should use in order to run this container on the host?
im personally dont even know what that sysctl set means I just want that container to run on my host and being able to connect to the VPN from the web and access my server.

appreciate any help

**Comment by aptalca** [comment] 2022-12-01 01:08
I don't know what you mean by `on the host`. 

But based on the last sentence, it sounds like you just want to run wireguard in server mode. Just follow the instructions on the readme for server mode. Then you'll be able to connect to it remotely and access the lan resources including the host machine.

**Comment by guyein** [comment] 2022-12-01 04:02
Thank you for the quick reply, and sorry by on the host I meant run it on the host network of the  ubuntu server and not on a bridge.

Still trying to figure out the networking configuration, thanks

**Comment by aptalca** [comment] 2022-12-01 04:57
You don't need to run it with host networking. For server mode, you don't really need to do any networking configuration. It just works.

**Comment by laurentlgm** [comment] 2023-02-03 09:54
The answer is that if you want to use the host network you have to set "sudo sysctl -w net.ipv4.conf.all.src_valid_mark=1" in the host not the container.
