### ISSUE TITLE
Passing torrent client through Wireguard

### ISSUE THREAD

**Issue by mouzzampk2014** [linuxserver/docker-wireguard#14] opened 2020-04-19 09:08 UTC
Hi, is it possible to pass qbittorrent from wireguard. So qbittorrrent use wireguard ip for connectivity and ports?

Thank you

**Comment by aptalca** [comment] 2020-04-19 15:00
Potentially, but not something we support at this time.

Closing this because it's not a bug report

**Closed by aptalca** 2020-04-19 15:00 UTC

**Comment by mouzzampk2014** [comment] 2020-04-19 15:07
Thank you for the update
