### ISSUE TITLE
[BUG] Default setup doesn't work with public ip?

### ISSUE THREAD

**Issue by thearchitector** [linuxserver/docker-wireguard#245] opened 2023-02-21 02:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would expect the default configuration to just work out of the box. It does seem to do so as long as I manually set `SERVERURL={local ip of server}`. I confirm if the VPN is running by trying to ping the server from the client `ping 10.13.13.1`.

When I set `SERVERURL=auto` or to my network's public IP, everything stops working on the client (it cannot connect to either the VPN nor the internet. If I change the client's `AllowedIPs` to `= 10.13.13.0/24`, public internet resolves again but I still cannot ping 10.13.13.1.

My router is configured to port forward requests from the public IP to the server. The server is running on Windows, but I've configured Windows Firewall to Allow both Incoming and Outgoing UDP traffic on 51820.

Am I missing a configuration option or concept here?

### Steps To Reproduce

Using this `docker-compose.yaml` file, omitting the `PEERS=` environment variable when running server side.

### CPU architecture

x86-64

### Docker creation

The YAML is identical on the client and server, with the only difference being the `PEERS` env (not set on client).

```yaml
version: "2.1"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:alpine
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PEERS=1
    volumes:
      - ./config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

### Container logs

From the server:

```
wireguard  | [migrations] started
wireguard  | [migrations] no migrations found
wireguard  | 
wireguard  | -------------------------------------
wireguard  |           _         ()
wireguard  |          | |  ___   _    __
wireguard  |          | | / __| | |  /  \
wireguard  |          | | \__ \ | | | () |
wireguard  |          |_| |___/ |_|  \__/
wireguard  | 
wireguard  | 
wireguard  | Brought to you by linuxserver.io
wireguard  | -------------------------------------
wireguard  | 
wireguard  | To support the app dev(s) visit:
wireguard  | WireGuard: https://www.wireguard.com/donations/
wireguard  | 
wireguard  | To support LSIO projects visit:
wireguard  | https://www.linuxserver.io/donate/
wireguard  | -------------------------------------
wireguard  | GID/UID
wireguard  | -------------------------------------
wireguard  | 
wireguard  | User uid:    1000
wireguard  | User gid:    1000
wireguard  | -------------------------------------
wireguard  | 
wireguard  | Uname info: Linux 1f2c35b4cfa7 5.15.90.1-microsoft-standard-WSL2 #1 SMP Mon Feb 20 02:26:38 UTC 2023 x86_64 GNU/Linux
wireguard  | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard  | **** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
wireguard  | **** Server mode is selected ****
wireguard  | **** SERVERURL var is either not set or is set to "auto", setting external IP to auto detected value of {{ MY PUBLIC IP }} ****
wireguard  | **** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
wireguard  | **** Internal subnet is set to 10.13.13.0 ****
wireguard  | **** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
wireguard  | **** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
wireguard  | **** No wg0.conf found (maybe an initial install), generating 1 server and 1 peer/client confs ****
wireguard  | PEER 1 QR code (conf file is saved under /config/peer1):
wireguard  | {{ QR CODE HERE}}
wireguard  | [custom-init] No custom files found, skipping...
wireguard  | .:53
wireguard  | CoreDNS-1.10.0
wireguard  | linux/amd64, go1.19.4,
wireguard  | [#] ip link add wg0 type wireguard
wireguard  | [#] wg setconf wg0 /dev/fd/63
wireguard  | [#] ip -4 address add 10.13.13.1 dev wg0
wireguard  | [#] ip link set mtu 1420 up dev wg0
wireguard  | [#] ip -4 route add 10.13.13.2/32 dev wg0
wireguard  | [#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
wireguard  | [ls.io-init] done.
```

From the client:
```
wireguard  | [migrations] started
wireguard  | [migrations] no migrations found
wireguard  | 
wireguard  | -------------------------------------
wireguard  |           _         ()
wireguard  |          | |  ___   _    __
wireguard  |          | | / __| | |  /  \
wireguard  |          | | \__ \ | | | () |
wireguard  |          |_| |___/ |_|  \__/
wireguard  | 
wireguard  | 
wireguard  | Brought to you by linuxserver.io
wireguard  | -------------------------------------
wireguard  | 
wireguard  | To support the app dev(s) visit:
wireguard  | WireGuard: https://www.wireguard.com/donations/
wireguard  | 
wireguard  | To support LSIO projects visit:
wireguard  | https://www.linuxserver.io/donate/
wireguard  | -------------------------------------
wireguard  | GID/UID
wireguard  | -------------------------------------
wireguard  | 
wireguard  | User uid:    1000
wireguard  | User gid:    1000
wireguard  | -------------------------------------
wireguard  | 
wireguard  | Uname info: Linux 1f2c35b4cfa7 5.15.90.1-microsoft-standard-WSL2 #1 SMP Mon Feb 20 02:26:38 UTC 2023 x86_64 GNU/Linux
wireguard  | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard  | **** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
wireguard  | **** Client mode is selected ****
wireguard  | [custom-init] No custom files found, skipping...
wireguard  | **** Disabling CoreDNS ****
wireguard  | Warning: `/config/wg0.conf' is world accessible
wireguard  | [#] ip link add wg0 type wireguard
wireguard  | [#] wg setconf wg0 /dev/fd/63
wireguard  | [#] ip -4 address add 10.13.13.2 dev wg0
wireguard  | [#] resolvconf -a wg0 -m 0 -x
wireguard  | [#] wg set wg0 fwmark 51820
wireguard  | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
wireguard  | [#] ip -4 rule add not fwmark 51820 table 51820
wireguard  | [#] ip -4 rule add table main suppress_prefixlength 0
wireguard  | [#] iptables-restore -n
wireguard  | [ls.io-init] done.
```
```

**Comment by aptalca** [comment] 2023-02-21 02:59
Since you can connect locally, I'm assuming your client is on the same LAN. Your issue is likely hairpin nat (nat loopback) related. Try from outside of your network. If still having issues, double and triple check your port forwarding and all firewalls in between.

Closing as this is not a bug. You can try other support channels like discord or discourse for further help.

**Closed by aptalca** 2023-02-21 02:59 UTC

**Comment by thearchitector** [comment] 2023-02-21 03:15
Thank you! It was indeed that NAT loopback thing and connecting the client to my phone hotspot resolved the issue. Frankly, I'm a bit embarrassed for not having tried that -- I am not at all versed in networking, but slowly and surely is the name of the game I suppose...
