### ISSUE TITLE
IP 6 address

### ISSUE THREAD

**Issue by ironbone** [linuxserver/docker-wireguard#224] opened 2022-12-30 19:07 UTC
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

As I can see in documentation there is no possibility u set the IP6
When I use the proposed docker-compose file, I am able to connect etc. but when using, my local IP6 adders is still visible

### Reason for change

I'm not really hidden when my local computer use IP6

**Comment by drizuid** [comment] 2023-01-04 17:22
dupe of https://github.com/linuxserver/docker-wireguard/issues/225
see response there

**Closed by drizuid** 2023-01-04 17:22 UTC
Labels: invalid
