### ISSUE TITLE
Failed to install docker-wireguard on Centos 8

### ISSUE THREAD

**Issue by adirbd** [linuxserver/docker-wireguard#72] opened 2020-10-16 20:11 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

To work and create keys

## Current Behavior

The wireguard module is not active

## Steps to Reproduce

1.Installing centos 8
2.install docker and docker-compose
3.create docker-compose file
4.run docker-compose up -d

## Environment
**OS: CentOS 8 minimal
**CPU architecture:** x86_64
**How docker service was installed:**

From the official docker repo with https://get.docker.com/
## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Jerusalem
      - SERVERURL=adirbd.ddns.net  #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=8.8.8.8 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=192.168.1.0/24 #optional
    volumes:
      - /opt/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

## Docker logs

[root@centos8 wireguard-server]# docker-compose up -d
Creating network "wireguard-server_default" with the default driver
Creating wireguard ... done
[root@centos8 wireguard-server]# docker logs wireguard
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Uname info: Linux 42cf8fcb1319 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Error: Unknown device type.
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****

Thanks!!

**Comment by aptalca** [comment] 2020-10-16 20:16
It's explained in the readme that kernel headers cannot be downloaded for centos. You'd need to install the headers on host and map /usr/src

Closing as this is not a bug. Feel free to drop by our discord or forum

**Closed by aptalca** 2020-10-16 20:16 UTC

**Comment by uzairali001** [comment] 2021-11-22 20:11
> Thanks for opening your first issue here! Be sure to follow the [issue template](https://github.com/linuxserver/docker-wireguard/blob/master/.github/ISSUE_TEMPLATE.md)!

That's a dead link

**Comment by uzairali001** [comment] 2022-03-19 16:40
I've created the guide to run wireguard docker on Centos / Rocky Linux
https://github.com/uzairali001/docker-wireguard-rhel
