### ISSUE TITLE
[BUG] variable SERVERPORT ignored when generating wg_confs/wg0.conf

### ISSUE THREAD

**Issue by fire829** [linuxserver/docker-wireguard#359] opened 2024-10-20 16:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using not default port number server stucked. Reason is that in wg0.conf port number still default (51820). Changing it to appropriate value fix server work.

### Steps To Reproduce

In docker compose file use - SERVERPORT= 12345

### Environment

```markdown
- OS: Centos Stream 9
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
..
```

**Comment by aptalca** [comment] 2024-10-20 19:50
Dupe of several others. Please check existing issues

**Closed by aptalca** 2024-10-20 19:50 UTC
