### ISSUE TITLE
[BUG] Example docker compose not working

### ISSUE THREAD

**Issue by andzejsp** [linuxserver/docker-wireguard#253] opened 2023-04-08 12:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create lxc container Debian11-standard 11.3-1 , add static ip, forward default 51820 UPD port on router for the LXC container.

Install docker
Create docker-compose.yml
```
---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

Run docker compose

exec this to get the QR code

docker compose exec -it wireguard /app/show-peer 1

Download android wireguard app

Add tunnel

Turn on tunnel

Nothing... No network

### Expected Behavior

Just works?

### Steps To Reproduce

Create proxmox lxc container Debian11-standard 11.3-1 , add static ip, forward default 51820 UPD port on router for the LXC container.

Install docker
Create docker-compose.yml
```
---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

Run docker compose

exec this to get the QR code

docker compose exec -it wireguard /app/show-peer 1

Download android wireguard app

Add tunnel

Turn on tunnel

Nothing... No network

### Environment

```markdown
- OS:Debian11-standard 11.3-1 on proxmox 7.4
- How docker service was installed: as per docker documentation
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
root@wireguard:~/wireguard-server# docker logs 831196d884ee
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    0
User GID:    0
───────────────────────────────────────

Uname info: Linux 831196d884ee 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
**** Server mode is selected ****
**** SERVERURL var is either not set or is set to "auto", setting external IP to auto detected value of your.mama.com ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** Server mode is selected ****
**** Server related environment variables changed, regenerating 1 server and 1 peer/client confs ****
PEER 1 QR code (conf file is saved under /config/peer1):
█████████████████████████████████████████████████████████████████████

█████████████████████████████████████████████████████████████████████
[custom-init] No custom files found, skipping...
.:53
CoreDNS-1.10.1
linux/amd64, go1.20, 055b2c3
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
[ls.io-init] done.
root@wireguard:~/wireguard-server#
```

**Comment by andzejsp** [comment] 2023-04-08 12:52
```
root@wireguard:~# docker exec wireguard wg show
interface: wg0
  public key: key
  private key: (hidden)
  listening port: 51820

peer: other key
  preshared key: (hidden)
  endpoint: work-ip:51820
  allowed ips: 10.13.13.2/32
  latest handshake: 9 seconds ago
  transfer: 2.36 KiB received, 1.31 KiB sent
root@wireguard:~# 
```

**Comment by andzejsp** [comment] 2023-04-08 12:55
What do you mean make sure youre not on the same lan?

My home local network is 192.168.0.x 
My work local has the same

Could this be the problem? if so how do work it out?

**Comment by aptalca** [comment] 2023-04-08 13:21
There is a handshake so the ip and port are working. Next, you can look into dns

**Comment by andzejsp** [comment] 2023-04-08 13:30
> There is a handshake so the ip and port are working. Next, you can look into dns

uhm, not sure what to look for, i mean, the LXC contianer the server/host can access web and local networks no problem. The docker compose has the DNS on auto so it uses the host DNS. 

Even setting DNS manually in the compose file to the host DNS gives no results.

**Comment by aptalca** [comment] 2023-04-08 13:59
I don't have much else to go on. The server shows a handshake, which means there is a successful connection both ways.

You're telling me `it doesn't work` which in itself is not very precise. The connection is clearly working. But if you mean `The browser is not opening any webpages` then it could be an issue with dns, or your android app, etc.

Impossible for be to say. With that said, I use the wireguard app on Android almost daily and it works fine.

You can try a different client with access to proper troubleshooting tools like ping, curl, dig, etc.

Closing this as it's not a bug. You can ask for help in our discord or discourse.

**Closed by aptalca** 2023-04-08 13:59 UTC

**Comment by j0nnymoe** [comment] 2023-04-08 14:24
> What do you mean make sure youre not on the same lan?
> 
> My home local network is 192.168.0.x My work local has the same
> 
> Could this be the problem? if so how do work it out?

If you have conflicting subnets, your device isn't going to know where to route the traffic. 
Solution: make sure the subnets you're connecting to/from are different.

**Comment by andzejsp** [comment] 2023-04-08 14:31
> 

Well subnets are indeed the same, on client and on host, if we are talking about the subnetmask 255.255.255.0.  How am i supposed to use it if the subnets match? so if your local network is similar to the network your client is connecting from, it wont work?

Well its just garbage.. not gonna use this

**Comment by j0nnymoe** [comment] 2023-04-08 14:38
Subnet mask is not relevant. It's networking basics that you don't want conflicting/overlapping subnets, you would get this error regardless of the VPN software you were using.
